package utils

const (
	BaseURL = "https://%s"

	ContactEndpoint          = "/rest/contact/"
	ContactByIDEndpoint      = "/rest/contact/%s"
	ContactListEndpoint      = "/rest/contact/list"
	ContactImportEndpoint    = "/rest/contact/import"
	ContactCommentEndpoint   = "/rest/contact/%s/comments"
	ContactDataTagEndpoint   = "/rest/contact/%s/datatags"
	ContactTemplatesEndpoint = "/rest/contact/templates"
	ContactGroupsEndpoint    = "/rest/contact/groups"
	ContactFiltersEndpoint   = "/rest/contact/filters"

	TaskEndpoint          = "/rest/task"
	TaskByIDEndpoint      = "/rest/task/%d"
	TaskListEndpoint      = "/rest/task/list"
	TaskCommentsEndpoint  = "/rest/task/%d/comments"
	TaskDataTagEndpoint   = "/rest/task/%d/datatags"
	TaskTemplatesEndpoint = "/rest/task/templates"
	TaskRecurringEndpoint = "/rest/task/recurring"
	TaskFiltersEndpoint   = "/rest/task/filters"
	TaskChecklistEndpoint = "/rest/task/%d/checklist/list"
	TaskFilesEndpoint     = "/rest/task/%d/files"

	CommentByIDEndpoint = "/rest/comment/%s"

	DataTagByIDEndpoint        = "/rest/datatag/%d"
	DataTagEntryByKeyEndpoint  = "/rest/datatag/entry/%d"
	DataTagListEndpoint        = "/rest/datatag/list"
	DataTagEntriesListEndpoint = "/rest/datatag/%d/entry/list"

	FileByIDEndpoint          = "/rest/file/%d"
	FileDownloadEndpoint      = "/rest/file/%d/download"
	FileUploadEndpoint        = "/rest/file/"
	FileFromURLEndpoint       = "/rest/file/from-url/"
	FileAttachTaskEndpoint    = "/rest/file/%d/attach/task"
	FileAttachContactEndpoint = "/rest/file/%d/attach/contact"
	FileAttachProjectEndpoint = "/rest/file/%d/attach/project"

	ProjectEndpoint          = "/rest/project"
	ProjectByIDEndpoint      = "/rest/project/%d"
	ProjectListEndpoint      = "/rest/project/list"
	ProjectTemplatesEndpoint = "/rest/project/templates"
	ProjectGroupsEndpoint    = "/rest/project/groups"
	ProjectFilesEndpoint     = "/rest/project/%d/files"

	UserEndpoint          = "/rest/user"
	UserByIDEndpoint      = "/rest/user/%s"
	UserListEndpoint      = "/rest/user/list"
	UserPositionsEndpoint = "/rest/user/positions"
	UserGroupsEndpoint    = "/rest/user/groups"

	DirectoryByIDEndpoint        = "/rest/directory/%d"
	DirectoryListEndpoint        = "/rest/directory/list"
	DirectoryEntryEndpoint       = "/rest/directory/%d/entry/"
	DirectoryEntryByKeyEndpoint  = "/rest/directory/%d/entry/%d"
	DirectoryEntriesListEndpoint = "/rest/directory/%d/entry/list"
	DirectoryGroupsEndpoint      = "/rest/directory/groups"
	DirectoryFiltersEndpoint     = "/rest/directory/%s/filters"

	ProcessTaskEndpoint         = "/rest/process/task"
	ProcessTaskStatusesEndpoint = "/rest/process/task/%d/statuses"
	ProcessContactEndpoint      = "/rest/process/contact"

	ReportByIDEndpoint     = "/rest/report/%d"
	ReportListEndpoint     = "/rest/report/list"
	ReportStatusEndpoint   = "/rest/report/status/%s"
	ReportSaveListEndpoint = "/rest/report/%d/save/list"
	ReportSaveDataEndpoint = "/rest/report/%d/save/%d/data"
	ReportGenerateEndpoint = "/rest/report/%d/generate"

	ObjectByIDEndpoint     = "/rest/object/%d"
	ObjectStatusesEndpoint = "/rest/object/%d/statuses"
	ObjectListEndpoint     = "/rest/object/list"

	CustomFieldTypesEndpoint        = "/rest/customfield/type"
	CustomFieldDataTagEndpoint      = "/rest/customfield/datatag/%d"
	CustomFieldDirectoryEndpoint    = "/rest/customfield/directory/%d"
	CustomFieldMainEndpoint         = "/rest/customfield/main"
	CustomFieldMainByIDEndpoint     = "/rest/customfield/main/%d"
	CustomFieldTaskEndpoint         = "/rest/customfield/task"
	CustomFieldTaskByIDEndpoint     = "/rest/customfield/task/%d"
	CustomFieldTaskGroupEndpoint    = "/rest/customfield/group/task"
	CustomFieldContactEndpoint      = "/rest/customfield/contact"
	CustomFieldContactByIDEndpoint  = "/rest/customfield/contact/%s"
	CustomFieldContactGroupEndpoint = "/rest/customfield/group/contact"
	CustomFieldProjectEndpoint      = "/rest/customfield/project"
	CustomFieldProjectByIDEndpoint  = "/rest/customfield/project/%d"
	CustomFieldProjectGroupEndpoint = "/rest/customfield/group/project"
	CustomFieldUserEndpoint         = "/rest/customfield/user"
	CustomFieldUserByIDEndpoint     = "/rest/customfield/user/%s"
	CustomFieldUserGroupEndpoint    = "/rest/customfield/group/user"

	PingEndpoint    = "/ping"
	ChatAPIEndpoint = "/webchat/api"
)
