package utils

const (
	BaseURL = "https://%s.planfix.com/rest"

	ContactEndpoint          = "/contact/"
	ContactByIDEndpoint      = "/contact/%s"
	ContactListEndpoint      = "/contact/list"
	ContactImportEndpoint    = "/contact/import"
	ContactCommentEndpoint   = "/contact/%s/comments"
	ContactDataTagEndpoint   = "/contact/%s/datatags"
	ContactTemplatesEndpoint = "/contact/templates"
	ContactGroupsEndpoint    = "/contact/groups"
	ContactFiltersEndpoint   = "/contact/filters"

	TaskEndpoint          = "/task"
	TaskByIDEndpoint      = "/task/%d"
	TaskListEndpoint      = "/task/list"
	TaskCommentsEndpoint  = "/task/%d/comments"
	TaskDataTagEndpoint   = "/task/%d/datatags"
	TaskTemplatesEndpoint = "/task/templates"
	TaskRecurringEndpoint = "/task/recurring"
	TaskFiltersEndpoint   = "/task/filters"
	TaskChecklistEndpoint = "/task/%d/checklist/list"
	TaskFilesEndpoint     = "/task/%d/files"

	CommentByIDEndpoint = "/comment/%s"

	DataTagByIDEndpoint        = "/datatag/%d"
	DataTagEntryByKeyEndpoint  = "/datatag/entry/%d"
	DataTagListEndpoint        = "/datatag/list"
	DataTagEntriesListEndpoint = "/datatag/%d/entry/list"

	FileByIDEndpoint          = "/file/%d"
	FileDownloadEndpoint      = "/file/%d/download"
	FileUploadEndpoint        = "/file/"
	FileFromURLEndpoint       = "/file/from-url/"
	FileAttachTaskEndpoint    = "/file/%d/attach/task"
	FileAttachContactEndpoint = "/file/%d/attach/contact"
	FileAttachProjectEndpoint = "/file/%d/attach/project"

	ProjectEndpoint          = "/project"
	ProjectByIDEndpoint      = "/project/%d"
	ProjectListEndpoint      = "/project/list"
	ProjectTemplatesEndpoint = "/project/templates"
	ProjectGroupsEndpoint    = "/project/groups"
	ProjectFilesEndpoint     = "/project/%d/files"

	UserEndpoint          = "/user"
	UserByIDEndpoint      = "/user/%s"
	UserListEndpoint      = "/user/list"
	UserPositionsEndpoint = "/user/positions"
	UserGroupsEndpoint    = "/user/groups"

	DirectoryByIDEndpoint        = "/directory/%d"
	DirectoryListEndpoint        = "/directory/list"
	DirectoryEntryEndpoint       = "/directory/%d/entry/"
	DirectoryEntryByKeyEndpoint  = "/directory/%d/entry/%d"
	DirectoryEntriesListEndpoint = "/directory/%d/entry/list"
	DirectoryGroupsEndpoint      = "/directory/groups"
	DirectoryFiltersEndpoint     = "/directory/%s/filters"

	ProcessTaskEndpoint         = "/process/task"
	ProcessTaskStatusesEndpoint = "/process/task/%d/statuses"
	ProcessContactEndpoint      = "/process/contact"

	ReportByIDEndpoint     = "/report/%d"
	ReportListEndpoint     = "/report/list"
	ReportStatusEndpoint   = "/report/status/%s"
	ReportSaveListEndpoint = "/report/%d/save/list"
	ReportSaveDataEndpoint = "/report/%d/save/%d/data"
	ReportGenerateEndpoint = "/report/%d/generate"

	ObjectByIDEndpoint     = "/object/%d"
	ObjectStatusesEndpoint = "/object/%d/statuses"
	ObjectListEndpoint     = "/object/list"

	CustomFieldTypesEndpoint        = "/customfield/type"
	CustomFieldDataTagEndpoint      = "/customfield/datatag/%d"
	CustomFieldDirectoryEndpoint    = "/customfield/directory/%d"
	CustomFieldMainEndpoint         = "/customfield/main"
	CustomFieldMainByIDEndpoint     = "/customfield/main/%d"
	CustomFieldTaskEndpoint         = "/customfield/task"
	CustomFieldTaskByIDEndpoint     = "/customfield/task/%d"
	CustomFieldTaskGroupEndpoint    = "/customfield/group/task"
	CustomFieldContactEndpoint      = "/customfield/contact"
	CustomFieldContactByIDEndpoint  = "/customfield/contact/%s"
	CustomFieldContactGroupEndpoint = "/customfield/group/contact"
	CustomFieldProjectEndpoint      = "/customfield/project"
	CustomFieldProjectByIDEndpoint  = "/customfield/project/%d"
	CustomFieldProjectGroupEndpoint = "/customfield/group/project"
	CustomFieldUserEndpoint         = "/customfield/user"
	CustomFieldUserByIDEndpoint     = "/customfield/user/%s"
	CustomFieldUserGroupEndpoint    = "/customfield/group/user"

	PingEndpoint    = "/ping"
	ChatAPIEndpoint = "/webchat/api"
)
